# Hydra config for Dataset/pattern.py runner
phase: train
output_names:
  train: all_model/train
  valid: toy_all_model/valid
  test: toy_all_model/test

output_name: ${output_names.${phase}}

input: dataset/liver_model/liver.dat
liver:
  E: 0.683
  nu: 0.49
tumor:
  E: 3.415
  nu: 0.40
max_disp: 30.0
train_divisions: 4
valid_count: 50
test_count: 50
max_nodes: null
seed: 42
plot_random: false
target_nodes: 100


hydra:
  run:
    dir: /workspace/config/dataset