# Hydra config for Dataset/pattern.py runner

# mode: train
# output_name: toy_all_model/train

# mode: valid
# output_name: toy_all_model/valid

mode: test
output_name: toy_all_model/test

input: dataset/liver_model/liver.dat
liver:
  E: 0.683
  nu: 0.49
tumor:
  E: 3.415
  nu: 0.40
max_disp: 30.0
train_divisions: 6
valid_count: 50
test_count: 50
max_nodes: null
seed: 42
plot_random: false


hydra:
  run:
    dir: /workspace/config/dataset